# Generated by Django 3.1.6 on 2021-03-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='atracoes'),
        ),
    ]
