# Generated by Django 3.1.6 on 2021-02-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('avaliacoes', '0001_initial'),
        ('comentarios', '0001_initial'),
        ('localizacoes', '0001_initial'),
        ('pontos_turisticos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='atracao',
            field=models.ManyToManyField(blank=True, null=True, to='atracoes.Atracao'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='avaliacao',
            field=models.ManyToManyField(blank=True, null=True, to='avaliacoes.Avaliacao'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='comentarios',
            field=models.ManyToManyField(blank=True, null=True, to='comentarios.Comentario'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='localizacao',
            field=models.ManyToManyField(blank=True, null=True, to='localizacoes.Localizacao'),
        ),
    ]
