# Generated by Django 3.1.6 on 2021-02-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('atracoes', '0001_initial'),
        ('avaliacoes', '0001_initial'),
        ('localizacoes', '0001_initial'),
        ('pontos_turisticos', '0002_auto_20210217_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='atracao',
            field=models.ManyToManyField(to='atracoes.Atracao'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='avaliacao',
            field=models.ManyToManyField(to='avaliacoes.Avaliacao'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.Comentario'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='localizacao',
            field=models.ManyToManyField(to='localizacoes.Localizacao'),
        ),
    ]
