# Generated by Django 3.1.6 on 2021-03-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos_turisticos', '0003_auto_20210217_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
